### PR TITLE
[MRG] add mastiff interface functions

### PR DESCRIPTION
**Pull request by bluegenes**
Add code for indexing and searching mastiff-style databases.

Branchwater `manysearch` and `fastmultigather` now accept an indexed database as an alternative to a text file:

## Index signatures into a mastiff-style database:
```
sourmash scripts index podar-ref-list.txt -o podar-ref.rdb
```
You can then use the 'check' functionality to check the mastiff index is 'ok':
```
sourmash scripts check podar-ref.rdb
```
Then, you can provide this database to either `manysearch` or `fastmultigather` in place of the reference file list.

## ManySearch
This command will use the current branchwater parallelization approach:
```
sourmash scripts manysearch query-list.txt podar-ref-list.txt -o ms-test.csv
```
while this one searches the mastiff-style database:
```
sourmash scripts manysearch query-list.txt podar-ref.rdb -o ms-test.mastiff.csv
```
**Search results differ slightly:**
- mastiff search doesn't provide the 'match_md5'

## Fastmultigather

This command will use the current branchwater parallelization approach:
```
sourmash scripts fastmulitgather query-list.txt podar-ref-list.txt
```
while this one gathers against the mastiff-style database:
```
sourmash scripts fastmultigather query-list.txt podar-ref.rdb -o g.csv
```
**Gather results differ in a few ways:**
- mastiff gather doesn't provide the 'gather_filename' or 'rank' columns
- mastiff gather does not provide prefetch results
- mastiff gather writes results from all queries into a single 'csv' file

## Notes on Multithreading

The Mastiff-style database is a fast on-disk storage that doesn't seem to benefit much from increasing threading. @luizirber any thoughts here?

### GTDB Reps (85k sigs): 40min; 6.7G database
```
time sourmash scripts index gtdb-rs214-reps.k31.zip -o gtdb-rs214-reps.k31.rdb

real    39m56.399s
user    33m57.385s
sys     5m51.034s
```

### Full GTDB (392k sigs): 3h 40min; 21G database
```
time sourmash scripts index gtdb-rs214-k31.zip -o gtdb-rs214.k31.rdb

real    217m24.231s
user    183m19.754s
sys     32m58.711s
```
> Note that there are 402,709 sigs in the GTDB-rs214 zip manifest, meaning that there are 392k unique md5sums. Here, we are thus only keeping information for one sig with each duplicated md5sum (losing the identifying information for the rest). Not ideal, but we don't yet have a good method for dealing with duplicate md5sum sigs in standard sourmash either...

### GTDB Reps (85k sigs; 6.7G database): 1min26s

**with 64 queries (podar-ref-list.txt as query list)**
```
time sourmash scripts gather podar-ref-list.txt /group/ctbrowngrp/sourmash-db/gtdb-
rs214/gtdb-rs214-reps.k31.rdb

== This is sourmash version 4.8.3. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

ksize: 31 / scaled: 1000 / threshold_bp: 50000
gathering all sketches in 'podar-ref-list.txt' against '/group/ctbrowngrp/sourmash-db/gtdb-rs214/gtdb-rs214-reps.k31.rdb' using 28 threads

DONE. Processed 64 search sigs
...gather is done!

real    1m26.296s
user    1m17.609s
sys     0m7.943s
```

### Full GTDB (392k sigs; 21G database): 2min

**with 64 queries (podar-ref-list.txt as query list)**
```
/usr/bin/time -v sourmash scripts gather podar-ref-list.txt gtdb-rs214.k31.rdb -o test2.csv -t 0 -c 1

== This is sourmash version 4.8.3. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

ksize: 31 / scaled: 1000 / threshold_bp: 0.0
DONE. Processed 64 search sigs
...gather is done! results in 'test2.csv'
       
 Command being timed: "sourmash scripts gather podar-ref-list.txt /group/ctbrowngrp/sourmash-db/gtdb-rs214/gtdb-rs214.k31.rdb -o test2.csv -t 0 -c 1"
        User time (seconds): 111.48
        System time (seconds): 9.53
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 2:01.68
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 1008332
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 1396431
        Voluntary context switches: 3777
        Involuntary context switches: 709
        Swaps: 0
        File system inputs: 0
        File system outputs: 80
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

## Code Source

The meat of the code here is adapted from https://github.com/sourmash-bio/mastiff (orig https://github.com/luizirber/2022-06-26-rocksdb-eval)

Note: this currently relies on a branch of sourmash core code with mastiff index (https://github.com/sourmash-bio/sourmash/tree/ntp/mastiff_roaring_prot). This code should be in `core` as of 0.12.0.

### CODE REVIEW

**Comment by bluegenes** [comment]
check downsampling?

**Comment by bluegenes** [comment]
@ctb  I think this is cleaner now: it avoids adding more search/gather to the CLI interface by running mastiff version of search/gather when the provided 'against' siglist appears to be a revindex. This means we can use the same tests for 'search', eliminating a bunch of nearly identical tests. Not entirely so for gather b/c outputs are different.

what remains:
- more mastiff gather testing
- understand CI failures

Ofc, I'm leaving any actual integration of the search/gather rust functions to you :slightly_smiling_face:

**Comment by ctb** [comment]
@bluegenes don't worry about the CI failures - please just finish with the gather testing! Thanks!

**Comment by bluegenes** [comment]
@ctb Ok, this is ready for review, then!

I tried a couple pkg updates over in the underlying sourmash core branch, but no luck on fixing #79. So hopefully changes as part of #20 will fix :)

**Comment by ctb** [comment]
thanks @bluegenes! It looks good to me - do you mind if I poke around with it a bit before merging? I think it's probably perfectly usable as a branch, but if you need it merged / released for some reason, let me know.

**Comment by ctb** [comment]
cool! I'm going to declare victory on the new CI - they're down to about 3m now, with caching of conda & rust. 🎉

**Comment by ctb** [comment]
updated benchmarks here: https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/81

**Pull request merged**
